<?php
	error_reporting(0);
	$__ctn = array(
		'event'=>array('Event Dâng Hoa Quốc Khánh(Event tiền vạn)', 'su_kien', '03-09-2018', '/lib/library/images/poster/default.jpg'),
		'opensever'=>array('Sự Kiện Khai Mở Sever Nam Hải 14h 1/9/2018', 'tin_tuc', '29-08-2018', '/lib/library/images/open%20moi2.png'),
		'congthanh7tru'=>array('Hoạt Động Thất Thành Đại Chiến', 'su_kien', '24-08-2018', '/lib/library/images/poster/default.jpg'),
		'thuthanh'=>array('Hoạt dộng phong hỏa liên thành(thủ thành)', 'su_kien', '24-08-2018', '/lib/library/images/poster/default.jpg'),
		'quockhanhnew'=>array('Event Trao Cờ Quốc Khánh Nhận Quà Khủng(Event xu)', 'su_kien', '24-08-2018', '/lib/library/images/poster/default.jpg'),
		'tai-tro-choi'=>array('Đường dẫn tải game và hướng dẫn cài đặt trò chơi', 'tin_tuc', '24-08-2018', '/lib/library/images/loi%20vo%20lam.PNG'),
		'tongkim'=>array('Hoạt động Tống Kim', 'su_kien', '24-08-2018', '/lib/library/images/poster/default.jpg'),
		'giohoatdong'=>array('Giờ Giấc Hoạt Động Trong Game', 'tin_tuc', '23-08-2018', '/lib/library/images/poster/default.jpg'),
		'sualoiauto'=>array('Hướng Dẫn Sữa Lỗi Auto', 'tin_tuc', '23-08-2018', '/lib/library/images/poster/default.jpg'),
		'cauca'=>array('Hoạt Động Câu Cá', 'su_kien', '15-08-2018', '/lib/library/images/poster/default.jpg'),
		'trungsinh'=>array('Tính Năng Trùng Sinh Nhân Vật', 'tinh_nang', '06-08-2018', '/lib/library/images/poster/default.jpg'),
		'viemde'=>array('Hoạt Động Viêm Đế', 'su_kien', '04-08-2018', '/lib/library/images/poster/default.jpg'),
		'ephoangkim'=>array('Ép Đồ Hoàng Kim', 'tinh_nang', '04-08-2018', '/lib/library/images/poster/default.jpg'),
		'tuyenchien'=>array('Tuyên Chiến Bang Hội', 'tinh_nang', '04-08-2018', '/lib/library/images/poster/default.jpg'),
		'ramanh'=>array('Rã mảnh Hoàng Kim ', 'tinh_nang', '04-08-2018', '/lib/library/images/poster/default.jpg'),
		'abhoanmy'=>array('Ép Ang Bang Hoàn Mỹ', 'tinh_nang', '04-08-2018', '/lib/library/images/poster/default.jpg'),
		'bossdai'=>array('Hoạt Động Săn Boss Đại Hoàng Kim', 'su_kien', '04-08-2018', '/lib/library/images/poster/default.jpg'),
		'daichienhoasaon'=>array('Hoạt Động Đại Chiến Hoa Sơn', 'su_kien', '04-08-2018', '/lib/library/images/poster/default.jpg'),
		'thientu'=>array('Hoạt Động Quốc Chiến Thiên Tử', 'su_kien', '04-08-2018', '/lib/library/images/poster/default.jpg'),
		'epdotim'=>array('Tính Năng Ép Đồ Tím', 'tinh_nang', '03-08-2018', '/lib/library/images/poster/default.jpg'),
		'16bit'=>array('Hướng Dẫn Chỉnh Màn Hình về 16bit', 'tin_tuc', '03-08-2018', '/lib/library/images/poster/default.jpg'),
		'bosssatthu'=>array('Hoạt Động Săn Boss Sát Thủ', 'su_kien', '03-08-2018', '/lib/library/images/poster/default.jpg'),
		'datau'=>array('Hoạt Động Dã Tẩu', 'su_kien', '03-08-2018', '/lib/library/images/poster/default.jpg'),
		'vuotai'=>array('Hoạt Động Vượt Ải', 'su_kien', '03-08-2018', '/lib/library/images/poster/default.jpg'),
		'phonglangdo'=>array('Hoạt Động Phong Lăng Độ', 'su_kien', '03-08-2018', '/lib/library/images/poster/default.jpg'),
		'liendau'=>array('Hoạt Động Liên Đấu', 'su_kien', '03-08-2018', '/lib/library/images/poster/default.jpg'),
		'bosstieu'=>array('Hoạt Động Săn Boss Tiểu Hoàng Kim', 'su_kien', '03-08-2018', '/lib/library/images/poster/default.jpg'),
		'longdenbanghoi'=>array('Hoạt Động Lồng Đèn Bang Hội', 'su_kien', '03-08-2018', '/lib/library/images/poster/default.jpg'),
		'congchua'=>array('Hoạt Động Giải Cứu Công Chúa', 'su_kien', '03-08-2018', '/lib/library/images/poster/default.jpg'),
		'hoatđộngthiêntử'=>array('Hoạt Động Quốc Chiến Thiên Tử', 'su_kien', '03-08-2018', '/lib/library/images/poster/default.jpg'),
		'đạichiếnhoason'=>array('Hoạt Động Đại Chiến Hoa Sơn', 'su_kien', '03-08-2018', '/lib/library/images/poster/default.jpg'),
		'chienlongdong'=>array('Hoạt động Chiến Long Động', 'su_kien', '03-08-2018', '/lib/library/images/poster/default.jpg'),
		'vantieu'=>array('Hoạt Động Vận Tiêu', 'su_kien', '03-08-2018', '/lib/library/images/poster/default.jpg'),
	);
?>
